# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

from Edge_Client_RP1 import Edge_Client_RP1


class ui_Checkout(QMainWindow):
    _translate = QtCore.QCoreApplication.translate
    def __init__(self):
        super(ui_Checkout, self).__init__()
        self.init_ui()

  
        self.password = ""
        self.show_pw = ""
        
    def init_ui(self):
        MainWindow = self
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(110, 10, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(40)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")
        self.RETURN = QtWidgets.QPushButton(self.centralwidget)
        self.RETURN.setGeometry(QtCore.QRect(130, 500, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.RETURN.setFont(font)
        self.RETURN.setObjectName("RETURN")
        self.label_pw = QtWidgets.QLabel(self.centralwidget)
        self.label_pw.setGeometry(QtCore.QRect(50, 110, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.label_pw.setFont(font)
        self.label_pw.setObjectName("label_pw")
        self.CART = QtWidgets.QPushButton(self.centralwidget)
        self.CART.setGeometry(QtCore.QRect(250, 310, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.CART.setFont(font)
        self.CART.setObjectName("CART")
        self.Show_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Show_Password.setGeometry(QtCore.QRect(180, 110, 200, 40))
        self.Show_Password.setText("")
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.Show_Password.setFont(font)        
        self.Show_Password.setObjectName("Show_Password")
        self.NUM_1 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_1.setGeometry(QtCore.QRect(20, 170, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_1.setFont(font)
        self.NUM_1.setObjectName("NUM_1")
        self.NUM_2 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_2.setGeometry(QtCore.QRect(90, 170, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_2.setFont(font)
        self.NUM_2.setObjectName("NUM_2")
        self.NUM_3 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_3.setGeometry(QtCore.QRect(160, 170, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_3.setFont(font)
        self.NUM_3.setObjectName("NUM_3")
        self.NUM_6 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_6.setGeometry(QtCore.QRect(160, 250, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_6.setFont(font)
        self.NUM_6.setObjectName("NUM_6")
        self.NUM_5 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_5.setGeometry(QtCore.QRect(90, 250, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_5.setFont(font)
        self.NUM_5.setObjectName("NUM_5")
        self.NUM_4 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_4.setGeometry(QtCore.QRect(20, 250, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_4.setFont(font)
        self.NUM_4.setObjectName("NUM_4")
        self.NUM_9 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_9.setGeometry(QtCore.QRect(160, 330, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_9.setFont(font)
        self.NUM_9.setObjectName("NUM_9")
        self.NUM_8 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_8.setGeometry(QtCore.QRect(90, 330, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_8.setFont(font)
        self.NUM_8.setObjectName("NUM_8")
        self.NUM_7 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_7.setGeometry(QtCore.QRect(20, 330, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_7.setFont(font)
        self.NUM_7.setObjectName("NUM_7")
        self.NUM_0 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_0.setGeometry(QtCore.QRect(20, 410, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.NUM_0.setFont(font)
        self.NUM_0.setObjectName("NUM_0")
        self.DELETE = QtWidgets.QPushButton(self.centralwidget)
        self.DELETE.setGeometry(QtCore.QRect(90, 410, 141, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.DELETE.setFont(font)
        self.DELETE.setObjectName("DELETE")
        self.PAY = QtWidgets.QPushButton(self.centralwidget)
        self.PAY.setGeometry(QtCore.QRect(250, 230, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.PAY.setFont(font)
        self.PAY.setObjectName("PAY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.RETURN.clicked.connect(self.slot_btn_Return_function)
        self.CART.clicked.connect(self.slot_btn_CART_function)


        self.PAY.clicked.connect(self.slot_btn_PAY_function)
        self.DELETE.clicked.connect(self.slot_btn_DELETE_function)

        self.NUM_0.clicked.connect(self.slot_btn_NUM_0_function)
        self.NUM_1.clicked.connect(self.slot_btn_NUM_1_function)
        self.NUM_2.clicked.connect(self.slot_btn_NUM_2_function)
        self.NUM_3.clicked.connect(self.slot_btn_NUM_3_function)
        self.NUM_4.clicked.connect(self.slot_btn_NUM_4_function)
        self.NUM_5.clicked.connect(self.slot_btn_NUM_5_function)
        self.NUM_6.clicked.connect(self.slot_btn_NUM_6_function)
        self.NUM_7.clicked.connect(self.slot_btn_NUM_7_function)
        self.NUM_8.clicked.connect(self.slot_btn_NUM_8_function)
        self.NUM_9.clicked.connect(self.slot_btn_NUM_9_function)

    def slot_btn_PAY_function(self):
        rpi1 = Edge_Client_RP1()
        rpi1.scan()

        msg = rpi1.checkout(self.password)
        if msg["status"] == 0:
            self.hide()
            from Payment import ui_Pay
            self.f = ui_Pay()
            self.f.show()
        else:
            for i in range(len(self.password)):
                self._remove_one_astroid()
            self.hide()
            from Wrong_PW import ui_WrongPW
            self.f = ui_WrongPW()
            self.f.show()

    
    def slot_btn_DELETE_function(self):
        if len(self.password)!=0:
            self._remove_one_astroid()
            self.Show_Password.setText(self._translate("MainWindow", self.show_pw))
            #print(self.password)

    def slot_btn_NUM_0_function(self):
        self._add_one_astroid()
        self.password+="0"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))

    def slot_btn_NUM_1_function(self):
        self._add_one_astroid()
        self.password+="1"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))
        
    def slot_btn_NUM_2_function(self):
        self._add_one_astroid()
        self.password+="2"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))

    def slot_btn_NUM_3_function(self):
        self._add_one_astroid()
        self.password+="3"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))

    def slot_btn_NUM_4_function(self):
        self._add_one_astroid()
        self.password+="4"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))
        
    def slot_btn_NUM_5_function(self):
        self._add_one_astroid()
        self.password+="5"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))

    def slot_btn_NUM_6_function(self):
        self._add_one_astroid()
        self.password+="6"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))

    def slot_btn_NUM_7_function(self):
        self._add_one_astroid()
        self.password+="7"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))
        
    def slot_btn_NUM_8_function(self):
        self._add_one_astroid()
        self.password+="8"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))    

    def slot_btn_NUM_9_function(self):
        self._add_one_astroid()
        self.password+="9"
        self.Show_Password.setText(self._translate("MainWindow", self.show_pw))    


    def _add_one_astroid(self):
        self.show_pw +="*"
    def _remove_one_astroid(self):
        self.show_pw = self.show_pw[:-1]
        self.password = self.password[:-1]


    def slot_btn_CART_function(self):
        self.hide()
        from MyCart import ui_Cart
        self.f = ui_Cart()
        self.f.show()

    def slot_btn_Return_function(self):
        self.hide()
        from Menu import ui_Menu
        self.f = ui_Menu()
        self.f.show()

    def retranslateUi(self, MainWindow):
        
        MainWindow.setWindowTitle(self._translate("MainWindow", "CheckOut"))
        self.Welcome_banner.setText(self._translate("MainWindow", "Checkout"))
        self.RETURN.setText(self._translate("MainWindow", "Return"))
        self.label_pw.setText(self._translate("MainWindow", "Password"))
        self.Show_Password.setText(self._translate("MainWindow", ""))
        self.CART.setText(self._translate("MainWindow", "Cart"))
        self.NUM_1.setText(self._translate("MainWindow", "1"))
        self.NUM_2.setText(self._translate("MainWindow", "2"))
        self.NUM_3.setText(self._translate("MainWindow", "3"))
        self.NUM_6.setText(self._translate("MainWindow", "6"))
        self.NUM_5.setText(self._translate("MainWindow", "5"))
        self.NUM_4.setText(self._translate("MainWindow", "4"))
        self.NUM_9.setText(self._translate("MainWindow", "9"))
        self.NUM_8.setText(self._translate("MainWindow", "8"))
        self.NUM_7.setText(self._translate("MainWindow", "7"))
        self.NUM_0.setText(self._translate("MainWindow", "0"))
        self.DELETE.setText(self._translate("MainWindow", "Delete"))
        self.PAY.setText(self._translate("MainWindow", "Pay"))
