# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

import sys


from TFLite_detection_face import face_activate
from Edge_Client_Interface import Edge_Client_Interface
from speech_rec import voice_recognition


class ui_Find_Item(QMainWindow):

    def __init__(self):
        super(ui_Find_Item, self).__init__()
        self.init_ui()
        self.searched = False
        
    def init_ui(self):
        MainWindow=self
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(80, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(40)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")
        self.RETURN = QtWidgets.QPushButton(self.centralwidget)
        self.RETURN.setGeometry(QtCore.QRect(140, 510, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.RETURN.setFont(font)
        self.RETURN.setObjectName("RETURN")
        
        self.AUDIO = QtWidgets.QPushButton(self.centralwidget)
        self.AUDIO.setGeometry(QtCore.QRect(90, 130, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.AUDIO.setFont(font)
        self.AUDIO.setObjectName("AUDIO")
        
        self.INFO = QtWidgets.QPushButton(self.centralwidget)
        self.INFO.setGeometry(QtCore.QRect(100, 240, 251, 231))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.INFO.setFont(font)
        self.INFO.setObjectName("INFO")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.RETURN.clicked.connect(self.slot_btn_Return_function)
        self.AUDIO.clicked.connect(self.slot_btn_ITEM_function)
        self.INFO.clicked.connect(self.slot_btn_MAP_function)

    def slot_btn_ITEM_function(self):
        print("record audio here")# add speech recognition here

        item = self._getUserAudioInput()

        Edge_Client_Interface.sendRequestToFog(
            template.format(self.id, "path", {"item": item})) # change here
        message = Edge_Client_Interface.getReplyFromFog()
        if message["status"] == 0:
            # item name, region, price
            item_info = "heard APPLE\n Region A\n $5 per each" # default 
        else:
            print("Error:", message["content"]["msg"])



        self.searched = True
        _translate = QtCore.QCoreApplication.translate
        self.INFO.setText(_translate("MainWindow", item_info))


    def _getUserAudioInput(self, extra = "") -> str:
        result = voice_recognition() #str(input("Please type your " + subject + " " + extra + ": "))
        while(result == ""):
            result = voice_recognition()# str(input(subject + " can't be empty. Please retype your " + subject + ": "))
        return result


    def slot_btn_MAP_function(self):
        if self.searched:
            self.searched = False
            self.hide()
            from Map import ui_Map
            self.f = ui_Map()
            self.f.show()

    def slot_btn_Return_function(self):
        self.hide()
        from Menu import ui_Menu
        self.f = ui_Menu()
        self.f.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FindItem"))
        self.Welcome_banner.setText(_translate("MainWindow", "FIND ITEM"))
        self.RETURN.setText(_translate("MainWindow", "Return"))
        self.AUDIO.setText(_translate("MainWindow", "ITEM"))
        msg = "please click\nITEM and then\ntell us what\nyou are finding"
        self.INFO.setText(_translate("MainWindow", msg))

##    def parse(self,sentence):
##        s=""
##        for i in range(len(sentence)):
##            s+=sentence[i]
##            if i%20==9:
##                s+="\n"
##        return s
