# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

import sys

class ui_Pay(QMainWindow):
    def __init__(self):
        super(ui_Pay, self).__init__()
        self.init_ui()
        
    def init_ui(self):
        MainWindow = self
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(110, 10, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(40)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")
        
        self.RETURN = QtWidgets.QPushButton(self.centralwidget)
        self.RETURN.setGeometry(QtCore.QRect(20, 500, 180, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.RETURN.setFont(font)
        self.RETURN.setObjectName("RETURN")

        self.DONE = QtWidgets.QPushButton(self.centralwidget)
        self.DONE.setGeometry(QtCore.QRect(220, 500, 180, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.DONE.setFont(font)
        self.DONE.setObjectName("DONE")
        
        self.QR_code = QtWidgets.QLabel(self.centralwidget)
        self.QR_code.setGeometry(QtCore.QRect(80, 130, 281, 291))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.QR_code.setFont(font)
        self.QR_code.setObjectName("QR_code")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.RETURN.clicked.connect(self.slot_btn_Return_function)
        self.DONE.clicked.connect(self.slot_btn_DONE_function)


    def slot_btn_DONE_function(self):
        received = True
        if received:
            self.hide()
            from Main import First_UI
            self.f = First_UI()
            self.f.show()
        else:
            self.DONE.setText(_translate("MainWindow", "DENIED"))
            


    def slot_btn_Return_function(self):
        self.hide()
        from Menu import ui_Menu
        self.f = ui_Menu()
        self.f.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Welcome_banner.setText(_translate("MainWindow", "Payment"))
        self.RETURN.setText(_translate("MainWindow", "Return"))
        self.DONE.setText(_translate("MainWindow", "DONE"))
        self.QR_code.setText(_translate("MainWindow", "QR CODE"))
