# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

from NumKeypad import NumKeypad


class Register_phone(QMainWindow, NumKeypad):
    _translate = QtCore.QCoreApplication.translate
    def __init__(self, photo, parent = None):
        super(Register_phone, self).__init__(parent)
        self.parent = parent
        self.photo = photo
        self.password = ""
        self.show_pw = ""


    def slot_btn_NEXT_function(self):
        self.hide()
        from Register_pw import Register_pw
        self.f = Register_pw(self.photo, self.password, self.parent)
        self.f.show()

    def slot_btn_Return_function(self):
        self.hide()
        self.f = self.parent
        self.f.show()

    def retranslateUi(self, MainWindow):

        MainWindow.setWindowTitle(self._translate("MainWindow", "Register"))
        self.Welcome_banner.setText(self._translate("MainWindow", "Phone #"))

        self.RETURN.setText(self._translate("MainWindow", "Return"))
        self.label_pw.setText(self._translate("MainWindow", "Phone #"))
        self.Show_Password.setText(self._translate("MainWindow", ""))

        self.NEXT.setText(self._translate("MainWindow", "Next"))

        self.NUM_1.setText(self._translate("MainWindow", "1"))
        self.NUM_2.setText(self._translate("MainWindow", "2"))
        self.NUM_3.setText(self._translate("MainWindow", "3"))
        self.NUM_6.setText(self._translate("MainWindow", "6"))
        self.NUM_5.setText(self._translate("MainWindow", "5"))
        self.NUM_4.setText(self._translate("MainWindow", "4"))
        self.NUM_9.setText(self._translate("MainWindow", "9"))
        self.NUM_8.setText(self._translate("MainWindow", "8"))
        self.NUM_7.setText(self._translate("MainWindow", "7"))
        self.NUM_0.setText(self._translate("MainWindow", "0"))
        self.DELETE.setText(self._translate("MainWindow", "Delete"))