# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton
#import edge_ui_11
import time

class ui_RegionA(QMainWindow):
    def __init__(self):
        super(ui_RegionA, self).__init__()
        self.setupUi()
    
    
    def setupUi(self):
        self.setObjectName("Welcome~")
        self.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(40, 20, 301, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(48)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")

        self.RETURN = QtWidgets.QPushButton(self.centralwidget)
        self.RETURN.setGeometry(QtCore.QRect(140, 510, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.RETURN.setFont(font)
        self.RETURN.setObjectName("RETURN")
 
        self.IMAGE = QtWidgets.QLabel(self.centralwidget)
        self.IMAGE.setGeometry(QtCore.QRect(50, 140, 350, 350))
        self.IMAGE.setText("")
        self.IMAGE.setPixmap(QtGui.QPixmap("src/edge/rpi1/FileStorage/RegionA.jpg"))
        self.IMAGE.setScaledContents(True)
        self.IMAGE.setObjectName("IMAGE")

#        self.slot_btn_function()
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.RETURN.clicked.connect(self.slot_btn_Return_function)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RegionA"))
        self.Welcome_banner.setText(_translate("MainWindow", "Region A"))
        self.RETURN.setText(_translate("MainWindow", "Return"))




    def slot_btn_Return_function(self):
        self.hide()
        from Menu import ui_Menu
        self.f = ui_Menu()
        self.f.show()

