# -*- coding: utf-8 -*-

# Form implementation generated from reading rpi1 file '1.rpi1'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

from Edge_Client_RP1 import Edge_Client_RP1
from NumKeypad import NumKeypad


class Relogin_pw(QMainWindow, NumKeypad):
    _translate = QtCore.QCoreApplication.translate
    def __init__(self, userID, parent = None):
        super(Relogin_pw, self).__init__(parent)
        self.parent = parent
        self.userID = userID
        self.password = ""
        self.show_pw = ""

    def slot_btn_NEXT_function(self):
        rpi1 = Edge_Client_RP1()
        msg = rpi1.login_with_password(self.userID, self.password)

        # msg = {"status": 1}
        if msg["status"] == 0:
            self.hide()
            from Menu import ui_Menu
            self.f = ui_Menu()
            self.f.show()
        else:
            for i in range(len(self.password)):
                self._remove_one_astroid()
            self.hide()
            from Wrong_PW import ui_WrongPW
            self.f = ui_WrongPW(self)
            self.f.show()

    def slot_btn_Return_function(self):
        self.hide()
        self.f = self.parent
        self.f.show()

    def retranslateUi(self, MainWindow):

        MainWindow.setWindowTitle(self._translate("MainWindow", "Login"))
        self.Welcome_banner.setText(self._translate("MainWindow", "Password"))

        self.RETURN.setText(self._translate("MainWindow", "Return"))
        self.label_pw.setText(self._translate("MainWindow", "Password"))
        self.Show_Password.setText(self._translate("MainWindow", ""))

        self.NEXT.setText(self._translate("MainWindow", "Login"))
        
        self.NUM_1.setText(self._translate("MainWindow", "1"))
        self.NUM_2.setText(self._translate("MainWindow", "2"))
        self.NUM_3.setText(self._translate("MainWindow", "3"))
        self.NUM_6.setText(self._translate("MainWindow", "6"))
        self.NUM_5.setText(self._translate("MainWindow", "5"))
        self.NUM_4.setText(self._translate("MainWindow", "4"))
        self.NUM_9.setText(self._translate("MainWindow", "9"))
        self.NUM_8.setText(self._translate("MainWindow", "8"))
        self.NUM_7.setText(self._translate("MainWindow", "7"))
        self.NUM_0.setText(self._translate("MainWindow", "0"))
        self.DELETE.setText(self._translate("MainWindow", "Delete"))