# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
#sys.path = sys.path+['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/pi/.local/lib/python3.7/site-packages', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton
#import edge_ui_11



import time

from TFLite_detection_face import face_activate
from Edge_Client_Interface import Edge_Client_Interface
from speech_rec import voice_recognition

class First_UI(QMainWindow):
    def __init__(self):
        super(First_UI, self).__init__()
        self.setupUi()

        self.photo = None
        self.id = "rpi1_000"
        
    
    
    def setupUi(self):
        self.setObjectName("Welcome~")
        self.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(40, 20, 301, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(48)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")

        #valueChanged = pyqtSignal()
        self.btn = QPushButton('Login', self)
        self.btn.setGeometry(330, 100, 100, 60)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.btn.setFont(font)
        self.btn.clicked.connect(self.slot_btn_function)
 
        self.Discount = QtWidgets.QLabel(self.centralwidget)
        self.Discount.setGeometry(QtCore.QRect(30, 160, 400, 400))
        self.Discount.setText("")
        self.Discount.setPixmap(QtGui.QPixmap("./dis.jpg"))
        self.Discount.setScaledContents(True)
        self.Discount.setObjectName("Discount")

#        self.slot_btn_function()
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome"))
        self.Welcome_banner.setText(_translate("MainWindow", "Welcome!"))

##    def login(self):
##        self.switch_window.emit()

    def slot_btn_function(self):
        self.hide()
#        from TFLite_detection_face import face_activate
        # request, photo = face_activate()
        
        
        detect_person = True # face recognition here

        #request,self.photo = face_activate()
        request = "activate_system" # for debug
        while request != "activate_system":
            pass
            #request,self.photo = face_activate()


        request_name = self.photo
        info = {"face": request_name}
        Edge_Client_Interface.sendRequestToFog(template.format(self.id, "login", info))
        message = Edge_Client_Interface.getReplyFromFog()

        self.username = message["username"]#not sure
        
        if  message["status"] == 1:
            from Edge_ui_11 import ui_1_1
            self.s = ui_1_1()# register page
            self.s.show()
            
        elif message["status"] == 0:
            #print("login successfully")

            f = open("id_info.txt","w")
            for each in [self.photo,self.username]:
                f.write(f"{each}\n")
            f.close()
                
            
            from Menu import ui_Menu
            self.s = ui_Menu()
            self.s.show()

def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = First_UI()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
    

if __name__ == "__main__":
    main()



   











