# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton

import sys

class ui_Cart(QMainWindow):
    def __init__(self):
        super(ui_Cart, self).__init__()
        self.init_ui()
        
    def init_ui(self):
        MainWindow = self
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_banner = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_banner.setGeometry(QtCore.QRect(100, 20, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(40)
        self.Welcome_banner.setFont(font)
        self.Welcome_banner.setObjectName("Welcome_banner")
        self.RETURN = QtWidgets.QPushButton(self.centralwidget)
        self.RETURN.setGeometry(QtCore.QRect(240, 510, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.RETURN.setFont(font)
        self.RETURN.setObjectName("RETURN")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 341, 381))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CHECKOUT = QtWidgets.QPushButton(self.centralwidget)
        self.CHECKOUT.setGeometry(QtCore.QRect(20, 510, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.CHECKOUT.setFont(font)
        self.CHECKOUT.setObjectName("CHECKOUT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.RETURN.clicked.connect(self.slot_btn_Return_function)

        self.CHECKOUT.clicked.connect(self.slot_btn_Checkout_function)

    def slot_btn_Checkout_function(self):
        self.hide()
        from CheckOut import ui_Checkout
        self.f = ui_Checkout()
        self.f.show()


    def slot_btn_Return_function(self):
        self.hide()
        from Menu import ui_Menu
        self.f = ui_Menu()
        self.f.show()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Welcome_banner.setText(_translate("MainWindow", "My Cart"))
        self.RETURN.setText(_translate("MainWindow", "Return"))

        f= open("receipt.txt","r")
        msg = ""
        for each in f:
            msg += each 
        #msg = "Total Price: $14.36\n-------------------\nbottle: 3x$2.3     \napple: 2x$1.0      \npineapple: 1x$3.99 \nbanana: 1x$1.47    \n"

        self.label.setText(_translate("MainWindow", msg))
        self.CHECKOUT.setText(_translate("MainWindow", "Checkout"))
